name: verify

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Clean old reports
        run: npm run clean:reports

      - name: Cypress run on ${{ matrix.browser }}
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          browser: ${{ matrix.browser }}
          command: npm run cypress:run
        env:
          BASE_URL: http://localhost:3000
        continue-on-error: true

      - name: List report files for debugging
        if: always()
        run: |
          echo "Listing cypress/reports directory:"
          ls -la cypress/reports/ || echo "Reports directory doesn't exist"
          echo "Listing cypress/reports/mochawesome directory:"
          ls -la cypress/reports/mochawesome/ || echo "Mochawesome directory doesn't exist"

      - name: Store HTML Report (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.browser }}
          path: |
            cypress/reports/mochawesome/
          if-no-files-found: warn

      - name: Store Cypress screenshots (${{ matrix.browser }})
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ matrix.browser }}
          path: cypress/screenshots
